# Generated by Django 4.2.4 on 2023-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_aboutus_contactformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
